### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tulma95** [rescawen/Wenlei-Dai-Rankkauslista-Tsoha#1]
8.04 klo 18.33
### Dokumentointi:
Sovelluksen dokumentointi oli hyvin tehty. Userguide oli kattava ja auttoi ainakin minua ymmärtämään sivun toiminnan. Tietokantakaavio olisi ollut selkeämpi kuvaajana eikä vain tekstinä.
### User storyt:
Kirjautumaton käyttäjä ei voinut vielä klikata turnausta ja nähdä siitä lisää tietoa.
Käyttäjätarinat oli suurimmaksi osaksi toteutettu ja ne toimivat dokumentoinnissa määritetyllä tavalla.

### Huomattuja ongelmia:
Jos sama käyttäjä liittyy turnaukseen monta kertaa, selain näyttää error-sivun.
Turnauksen aloittaminen, jossa ei ole yhtään pelaajaa aiheuttaa errorin.
Turnauksien Match-numero taitaa käyttää samaa juoksevaa lukua tällä hetkellä, esimerkiksi turnauksessa 1 on ottelut 1-3 ja turnauksessa 2 on ottelut 4-5. En tiedä onko tämä tarkoitettua vai ei.
Jos turnaus, johon on liittynyt käyttäjiä, poistetaan, niin samat käyttäjät liittyvät automaattisesti seuravaksi luotuun turnaukseen. Näin saadaa esimerkiksi turnaukseen, jonka playercount on 2, 3 käyttäjää.
### Sivun käytettävyys:
Etusivulla listattuihin turnauksiin voisi kertoa, mitä sinisessä ympyrässä oleva numero tarkoittaa. 
Turnauksen sivulla, pelaajat ja ottelut voisi erotella toisistaan selkeämmin.
### Koodi:
Tietokanta tuli zip-paketin mukana, vaikka sen pitäisi olla gitignoressa. Koodi on selkeää ja helposti luettavaa. Muuttujanimet ovat kuvaavia ja niitä oli helppo seurata.

**Comment by rescawen** [comment]
Kiitos palautteesta, turnaus bracket frontissa ei ole edes aloitettu se olis jo suhteellisen vaikeata saada toimimaan backend:ssä joka on projektin prioritieetti. Ylipäätänsä hyvä lista asioita joita pitää korjata.
